# Setup
title:               IX Lab
tagline:             Interaction+X Lab
description:         
url:                 'https://cookingfoil.github.io/ixlab/'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Eunji Park
  url:               'https://cookingfoil.github.io/ixlab/'
  email:             eunjipark@cau.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
