# Setup
title:               HCI Lab
tagline:             Human-Computer Interaction Lab
description:         
# description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 'https://cookingfoil.github.io/hcilab'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Eunji Park
  url:               https://cookingfoil.github.io/hcilab
  email:             eunjipark@cau.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
